name: CI

on:
  push:
  pull_request:

jobs:
  elixir-specs-runner:
    runs-on: ubuntu-latest

    env:
      MIX_TERM_COLOR: true
      MIX_ENV: test

    defaults:
      run:
        working-directory: runners/elixir

    steps:
      - uses: actions/checkout@v5

      - name: Set up Erlang and Elixir
        uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Install dependencies
        run: mix deps.get

      - name: Check code
        run: mix check

      - name: Run Tests
        run: mix coveralls.github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
