name: CI

on:
  push:
  pull_request:

jobs:
  elixir-runner:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: runners/elixir

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Erlang and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '27.2'
          elixir-version: '1.18.3'

      - name: Install dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test
